import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{ts,tsx,mdx}',
    './components/**/*.{ts,tsx,mdx}',
    './content/**/*.{ts,tsx,mdx}',
    './data/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        heading: ['Plus Jakarta Sans', 'Space Grotesk', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      colors: {
        olive: {
          50: '#f5f8ec',
          100: '#e8f0d8',
          200: '#d2e3b5',
          300: '#b4d188',
          400: '#94be5f',
          500: '#75a440',
          600: '#5b8230',
          700: '#466427',
          800: '#2b3823',
          850: '#232e1c',
          900: '#1c2517',
          925: '#171e13',
          950: '#11170d',
        },
        gold: {
          50: '#fffdf5',
          100: '#fef9e7',
          200: '#fdf0c3',
          300: '#fce395',
          400: '#facc15',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        warm: {
          50: '#faf9f6',
          100: '#f5f4f0',
          200: '#eae8e1',
          300: '#d6d3c7',
          400: '#a8a599',
          500: '#7d7a6e',
          600: '#5c594f',
          700: '#434037',
          800: '#2b2923',
          900: '#1c1b17',
          950: '#12110e',
        },
      },
      boxShadow: {
        'glow-gold': '0 0 25px -5px rgba(245, 158, 11, 0.25)',
        'glow-gold-lg': '0 0 40px -10px rgba(245, 158, 11, 0.35)',
        'glow-olive': '0 0 30px -5px rgba(32, 41, 25, 0.5)',
      },
      typography: ({ theme }: { theme: (path: string) => string }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.warm.700'),
            '--tw-prose-headings': theme('colors.warm.900'),
            '--tw-prose-lead': theme('colors.warm.600'),
            '--tw-prose-links': theme('colors.emerald.600'),
            '--tw-prose-bold': theme('colors.warm.900'),
            '--tw-prose-counters': theme('colors.emerald.600'),
            '--tw-prose-bullets': theme('colors.emerald.500'),
            '--tw-prose-hr': theme('colors.warm.200'),
            '--tw-prose-quotes': theme('colors.warm.800'),
            '--tw-prose-quote-borders': theme('colors.emerald.500'),
            '--tw-prose-captions': theme('colors.warm.500'),
            '--tw-prose-code': theme('colors.emerald.700'),
            '--tw-prose-pre-code': theme('colors.warm.100'),
            '--tw-prose-pre-bg': theme('colors.olive.950'),
            '--tw-prose-th-borders': theme('colors.warm.300'),
            '--tw-prose-td-borders': theme('colors.warm.200'),
            'code::before': { content: '""' },
            'code::after': { content: '""' },
          },
        },
        invert: {
          css: {
            '--tw-prose-body': theme('colors.warm.300'),
            '--tw-prose-headings': theme('colors.warm.100'),
            '--tw-prose-lead': theme('colors.warm.400'),
            '--tw-prose-links': theme('colors.gold.400'),
            '--tw-prose-bold': theme('colors.warm.100'),
            '--tw-prose-counters': theme('colors.gold.400'),
            '--tw-prose-bullets': theme('colors.gold.500'),
            '--tw-prose-hr': theme('colors.olive.800'),
            '--tw-prose-quotes': theme('colors.warm.200'),
            '--tw-prose-quote-borders': theme('colors.gold.500'),
            '--tw-prose-captions': theme('colors.warm.400'),
            '--tw-prose-code': theme('colors.gold.300'),
            '--tw-prose-pre-code': theme('colors.warm.100'),
            '--tw-prose-pre-bg': theme('colors.olive.950'),
            '--tw-prose-th-borders': theme('colors.olive.800'),
            '--tw-prose-td-borders': theme('colors.olive.850'),
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};

export default config;
